on: [pull_request]

name: CI

jobs:
  verify:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          
      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REL }}

      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - run: just verify